;;;; router.import.scm - GENERATED BY CHICKEN 5.1.0 -*- Scheme -*-

(##sys#register-compiled-module
  'router
  'router
  (scheme#list)
  '((route . router#route) (build-table . router#build-table))
  (scheme#list)
  (scheme#list))

;; END OF FILE
