;;;; router.import.scm - GENERATED BY CHICKEN 5.2.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'router
      'router
      (scheme#list)
      '((route . router#route) (build-table . router#build-table))
      (scheme#list)
      (scheme#list))))

;; END OF FILE
