(import socket)
(import (chicken format))

(let* ((sock (socket af/inet sock/stream))
       (msg "GET /hello HTTP/1.0"))
  (socket-connect sock (inet-address "127.0.0.1" 2020))
  (let* ((number-of-bytes (socket-send sock msg))
        (msg-len 1024)
	(backlog 1)
        (received-data (socket-receive sock msg-len)))
    (printf "num of bytes sent: ~A~%" number-of-bytes)
    (printf "received back: '~A' ~%" received-data))
  (socket-close sock))
