;;;; test.import.scm - GENERATED BY CHICKEN 5.2.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'test
      'test
      (scheme#list)
      '((out . test#out))
      (scheme#list)
      (scheme#list))))

;; END OF FILE
